[build]
  publish = "."

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"
    X-Frame-Options = "SAMEORIGIN"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/encadrant"
  to = "/encadrant.html"
  status = 200

[[redirects]]
  from = "/apprenant"
  to = "/apprenant.html"
  status = 200

[[redirects]]
  from = "/qcm"
  to = "/qcm.html"
  status = 200
